[functions.unda-callback]
verify_jwt = false

[functions.mpesa-callback]
verify_jwt = false
[functions.settle-to-restaurant]
verify_jwt = false
import_map = "./functions/settle-to-restaurant/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/settle-to-restaurant/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/settle-to-restaurant/*.html" ]
